---
# deploy.yml

- name: Deploy Configurations to Devices using eAPI # (1)!
  hosts: FABRIC
  vars:
    ansible_command_timeout: 60
  gather_facts: false
  tasks:
    - name: Deploy Configurations to Devices # (2)!
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_eapi
